ingredients/urls.py
from django.urls import path
from .views import IngredientListView

app_name = 'ingredients'

urlpatterns = [
    path('', IngredientListView.as_view(), name='ingredients_home'),
]

recipe_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view

urlpatterns = [
    # we specify here that we want to use the admin site
    path('admin/', admin.site.urls),
    # we include the recipes.urls file to specify the URL configuration for the recipes app
    path('', include('recipes.urls')),  
    # path('ingredients/', include('ingredients.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('login/', include('allauth.urls')),
    path('ingredients/', include('ingredients.urls')),
    # path('ingredients/', include(('ingredients.urls', 'ingredients'), namespace='ingredients')),
    path('recipes/', include('recipes.urls')),
    

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from .views import RecipeListView, RecipeDetailView
from .views import records

# we specify the app_name variable to avoid confusion with other apps
app_name = 'recipes'

urlpatterns = [
    # we specify here that we want to use the home function 
    # from the views.py file when the user goes to the root URL
    path('',  RecipeListView.as_view(), name='recipes_home'),
    path('recipe/<int:pk>', RecipeDetailView.as_view(), name='recipe_detail'),
    path('', records, name='records'),
    path('search/', records, name='records'),
]

recipes/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

difficulty_choices = (
    ('easy', 'Easy'),
    ('medium', 'Medium'),
    ('hard', 'Hard')

)
class Recipe(models.Model):
    name = models.CharField(max_length=100)
    userid = models.ForeignKey('users.User', on_delete=models.CASCADE)
    description = models.TextField()
    ingredients = models.ManyToManyField('ingredients.Ingredient', related_name='recipes')
    cooking_time = models.PositiveIntegerField()
    difficulty = models.CharField(max_length=20, choices=difficulty_choices)
    pic = models.ImageField(upload_to='recipes', default='no_picture.png')

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('recipes:recipe_detail', kwargs={'pk': self.pk})

recipes/forms.py
from django import forms
from ingredients.models import Ingredient

CHART_CHOICES = (
    ('pie', 'Pie Chart'),
    ('bar', 'Bar Chart'),
    ('line', 'Line Chart'),
)

#define class-based form imported from django
class SearchForm(forms.Form):
    ingredient = forms.CharField(max_length=100, required=False)
    chart_type = forms.ChoiceField(choices=CHART_CHOICES, required=False)
    

recipes/views.py
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import ListView, DetailView
from .models import Recipe
from ingredients.models import Ingredient
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import pandas as pd
from .utils import get_username_from_id, get_chart



#to protect class-based view
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import SearchForm

# Create your views here.
class RecipeListView(ListView):
    model = Recipe
    template_name = 'recipes/recipes_home.html'


class RecipeDetailView(LoginRequiredMixin, DetailView): #class-based “protected” view
    model = Recipe
    template_name = 'recipes/recipe_detail.html'

def records(request):
    # create an instance of SearchForm and pass it to the template
    form = SearchForm(request.POST or None)

    # initialize variables
    ingredient_name = None # create an empty string to store the ingredient name
    recipes_with_ingredient = [] # create an empty list to store recipes with the ingredient
    search_df = None # create an empty dataframe to store the search results
    chart = None # create an empty string to store the chart
    ingredient_not_found = '' # create an empty string to store the ingredient not found 💆‍♂️ 
    recipe_not_found = '' # create a boolean to store the recipe not found

    # if the form is submitted and valid, then we will process the data
    if request.method == 'POST' and form.is_valid():
      # read ingredient and chart_type from the form
        ingredient_name = request.POST.get('ingredient').strip()
        chart_type = request.POST.get('chart_type')
        print(ingredient_name)
        print(chart_type)

        # get the ingredient object from the database
        try:
            ingredient = Ingredient.objects.filter(name__icontains=ingredient_name)

           
                # get the recipes that contain the ingredient
            recipes_with_ingredient = Recipe.objects.filter(ingredients__in=ingredient).distinct()

                # print ('recipes_with_ingredient : ')
                # print (recipes_with_ingredient)
                # print ('recipes_with_ingredient.values() : ')
                # print (recipes_with_ingredient.values())
                # print ('recipes_with_ingredient.values_list() : ')
                # print (recipes_with_ingredient.values_list())
                # print ('total_recipes : ')
                # print (total_recipes)

            if recipes_with_ingredient.exists():
                # create a dataframe from the recipes
                search_df = pd.DataFrame(list(recipes_with_ingredient.values()))

                # total number of recipes in the db for the chart
                total_recipes = Recipe.objects.all().count()

                # Generate HTML links for each recipe name
                search_df['Link'] = search_df.apply(lambda row: f'<a href="{reverse("recipes:recipe_detail", kwargs={"pk": row["id"]})}">{row["name"]}</a>', axis=1)


                # add a new column to the dataframe to store the username of the author
                search_df['author'] = search_df['userid_id'].apply(get_username_from_id)

                # add a new column to the dataframe to store the total number of recipes
                search_df['total_recipes'] = total_recipes

                # create a chart from the dataframe
                chart = get_chart(chart_type, search_df, labels=search_df['name'])

                # convert the dataframe to HTML
                search_df = search_df.to_html(escape=False)

            else:
                recipe_not_found = "Recipe not Found"

        except Ingredient.DoesNotExist:
                ingredient_not_found = 'Ingredient not Found'


    # pack up data to be sent to template in the context dictionary
    context = {
        'form': form,
        'search_df': search_df,
        'chart': chart,
        'ingredient_not_found': ingredient_not_found,
        'recipe_not_found': recipe_not_found,
    }
    print('ingredient_not_found : ')
    print(ingredient_not_found)
    print('recipe_not_found : ')
    print(recipe_not_found)

    # Load the sales/records.html template with the context dictionary

    return render(request, 'recipes/records.html', context)

recipes/templates/recipes/ingredients_home.html
<!DOCTYPE html>
{% load static %}
<html>
	<head>
		<title>Ingredients List</title>
		<link
			rel="stylesheet"
			href="{% static 'ingredients/css/ingredients.css' %}" />
	</head>
	<body>
		<div class="header">
			{% if not user.is_authenticated %}
			<a
				href="{% url 'login' %}"
				class="login-button"
				>Login</a
			>
			{% else %}
			<a
				href="{% url 'logout' %}"
				class="login-button"
				>Logout</a
			>
			<p class="username">Welcome, {{ user.username }}</p>
			{% endif %}
			<h1 class="page-title">INGREDIENTS</h1>
		</div>

		<div class="recipe-main-image">
			<img
				src="{% static 'recipes/images/recipes.webp' %}"
				alt="Main image of the site" />
		</div>
		<div class="search-bar">
			<form
				action="{% url 'ingredients:ingredients_home' %}"
				method="get">
				<input
					type="text"
					name="search"
					placeholder="Search for a ingredients..."
					value="{{ request.GET.search }}" />
				<button type="submit">Search</button>
			</form>
		</div>
		<div class="container">
			{% for ingredient in object_list %}
			<div class="ingredient-card">
				<div class="ingredient-image">
					<img
						src="{{ ingredient.pic.url }}"
						alt="{{ ingredient.name }}" />
				</div>
				<div class="ingredient-content">
					<h2 class="ingredient-name">{{ ingredient.name }}</h2>
				</div>
			</div>
			{% endfor %}
		</div>

		<div class="footer">© 2024 Recipe App - All rights reserved.</div>
	</body>
</html>

recipes/templates/recipes/recipe_detail.html
<!DOCTYPE html>
{% load static %}
<html>
	<head>
		<title>{{ recipe.name }} - Recipe Details</title>
		<link
			rel="stylesheet"
			href="{% static 'recipes/css/recipes.css' %}" />
	</head>
	<body>
		<div class="header">
			{% if not user.is_authenticated %}
			<a
				href="{% url 'login' %}"
				class="login-button"
				>Login</a
			>
			{% else %}
			<a
				href="{% url 'logout' %}"
				class="login-button"
				>Logout</a
			>
			<p class="username">Welcome, {{ user.username }}</p>

			{% endif %}
			<h1 class="page-title">LES RECETTES DE LUCETTE</h1>
		</div>

		<div class="container-detail">
			<div class="recipe-image-detail">
				<img
					src="{{ recipe.pic.url }}"
					alt="{{ recipe.name }}" />
			</div>
			<h1 class="recipe-name">{{ recipe.name }}</h1>
			<div class="recipe-content-detail">
				<div>
					<p><strong>Description:</strong> {{ recipe.description }}</p>
					<p><strong>Cooking Time:</strong> {{ recipe.cooking_time }} minutes</p>
					<p><strong>Difficulty:</strong> {{ recipe.get_difficulty_display }}</p>
				</div>
				<div>
					<!-- <p style="text-align: center"><strong>Ingredients :</strong></p> -->
					<a
						href="{% url 'ingredients:ingredients_home' %}"
						style="text-decoration: none; color: inherit">
						<p style="text-align: center"><strong>Ingredients :</strong></p>
					</a>

					<ul>
						{% for ingredient in recipe.ingredients.all %}
						<li>{{ ingredient.name }}</li>
						{% endfor %}
					</ul>
				</div>
			</div>
			<a
				href="{% url 'recipes:recipes_home' %}"
				class="details-button"
				>Back to Recipes</a
			>
		</div>
		<div class="footer">© 2024 Recipe App - All rights reserved.</div>
	</body>
</html>

recipes/templates/recipes/recipes_home.html
<!DOCTYPE html>
{% load static %}
<html>
	<head>
		<title>Recipe App</title>
		<link
			rel="stylesheet"
			href="{% static 'recipes/css/recipes.css' %}" />
	</head>
	<body>
		<div class="header">
			{% if not user.is_authenticated %}
			<a
				href="{% url 'login' %}"
				class="login-button"
				>Login</a
			>
			{% else %}
			<a
				href="{% url 'logout' %}"
				class="login-button"
				>Logout</a
			>
			<p class="username">Welcome, {{ user.username }}</p>
			{% endif %}
			<h1 class="page-title">LES RECETTES DE LUCETTE</h1>
		</div>

		<div class="recipe-main-image">
			<img
				src="{% static 'recipes/images/recipes.webp' %}"
				alt="Main image of the site" />
		</div>
		<div class="search-bar">
			<form
				action="{% url 'recipes:recipes_home' %}"
				method="get">
				<input
					type="text"
					name="search"
					placeholder="Search for a recipe..."
					value="{{ request.GET.search }}" />
				<button type="submit">Search</button>
			</form>
		</div>
		<div class="container">
			{% for recipe in object_list %}
			<div class="recipe-card">
				<div class="recipe-image">
					<img
						src="{{ recipe.pic.url }}"
						alt="{{ recipe.name }}" />
				</div>
				<div class="recipe-content">
					<!-- <h2 class="recipe-name">{{ recipe.name }}</h2> -->
					<h2 class="recipe-name">
						<a href="{{ recipe.get_absolute_url }}">{{ recipe.name }}</a>
					</h2>
					<p class="recipe-description">{{ recipe.description }}</p>
					<a
						href="{{ recipe.get_absolute_url }}"
						class="details-button"
						>Details</a
					>
				</div>
			</div>
			{% endfor %}
		</div>
		<div class="footer">© 2024 Recipe App - All rights reserved.</div>
	</body>
</html>

recipes/templates/recipes/records.html
<!DOCTYPE html>
{% load static %}
<html>
	<head>
		<title>Search For Ingredients</title>
		<link
			rel="stylesheet"
			href="{% static 'recipes/css/search.css' %}" />
	</head>
	<br />
	<body>
		<div class="header">
			{% if not user.is_authenticated %}
			<a
				href="{% url 'login' %}"
				class="login-button"
				>Login</a
			>
			{% else %}
			<a
				href="{% url 'logout' %}"
				class="login-button"
				>Logout</a
			>
			<p class="username">Welcome, {{ user.username }}</p>
			{% endif %}
			<h1 class="page-title">SEARCH</h1>
		</div>
		<br />
		<form
			style="text-align: center"
			action=""
			method="POST">
			{% csrf_token %} {{form}}
			<button type="submit">search</button>
		</form>
		<br />
		{% if search_df %} {{search_df |safe}}

		<br />
		<p style="text-align: center">Cooking time per recipe</p>
		<img
			style="text-align: center"
			src="data:image/png;base64,{{ chart|safe }}" />
		{% else %}

		<h3>No data. {{ingredient_not_found}} {{recipe_not_found}}</h3>
		{% endif %}
	</body>
</html>